repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml

  - repo: local
    hooks:
      - id: swiftformat
        name: swiftformat
        entry: swiftformat --lint .
        language: system
        types: [swift]
        pass_filenames: false

      - id: swiftlint
        name: swiftlint
        entry: swiftlint
        language: system
        types: [swift]
        pass_filenames: false
